/*
Sonatype IQ Server

Testing PolicyWaiverAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	iqclient "github.com/sonatype-nexus-community/nexus-iq-api-client-go"
)

func Test_openapi_PolicyWaiverAPIService(t *testing.T) {

	configuration := iqclient.NewConfiguration()
	apiClient := iqclient.NewAPIClient(configuration)

	t.Run("Test PolicyWaiverAPIService AddPolicyWaiver", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var policyViolationId string
		var ownerType string

		httpRes, err := apiClient.PolicyWaiverAPI.AddPolicyWaiver(context.Background(), policyViolationId, ownerType).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
