/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.204.2-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ApiWaiverOptionsDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiWaiverOptionsDTO{}

// ApiWaiverOptionsDTO Options for creating policy waivers
type ApiWaiverOptionsDTO struct {
	// Reason for waiving the violation(s). Must be non-blank.
	Comment string `json:"comment"`
	// If true, the waiver will automatically expire when a remediation becomes available. Can only be set to true when matcherStrategy is EXACT_COMPONENT.
	ExpireWhenRemediationAvailable *bool `json:"expireWhenRemediationAvailable,omitempty"`
	// Optional expiration date/time for the waiver in ISO 8601 format. Must be in the future if provided.
	ExpiryTime *time.Time `json:"expiryTime,omitempty"`
	// Component matching strategy. For Firewall bulk waivers, only EXACT_COMPONENT and ALL_VERSIONS are supported.
	MatcherStrategy string `json:"matcherStrategy"`
	// Optional reference to a pre-defined waiver reason ID
	WaiverReasonId *string `json:"waiverReasonId,omitempty"`
}

type _ApiWaiverOptionsDTO ApiWaiverOptionsDTO

// NewApiWaiverOptionsDTO instantiates a new ApiWaiverOptionsDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiWaiverOptionsDTO(comment string, matcherStrategy string) *ApiWaiverOptionsDTO {
	this := ApiWaiverOptionsDTO{}
	this.Comment = comment
	this.MatcherStrategy = matcherStrategy
	return &this
}

// NewApiWaiverOptionsDTOWithDefaults instantiates a new ApiWaiverOptionsDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiWaiverOptionsDTOWithDefaults() *ApiWaiverOptionsDTO {
	this := ApiWaiverOptionsDTO{}
	return &this
}

// GetComment returns the Comment field value
func (o *ApiWaiverOptionsDTO) GetComment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Comment
}

// GetCommentOk returns a tuple with the Comment field value
// and a boolean to check if the value has been set.
func (o *ApiWaiverOptionsDTO) GetCommentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Comment, true
}

// SetComment sets field value
func (o *ApiWaiverOptionsDTO) SetComment(v string) {
	o.Comment = v
}

// GetExpireWhenRemediationAvailable returns the ExpireWhenRemediationAvailable field value if set, zero value otherwise.
func (o *ApiWaiverOptionsDTO) GetExpireWhenRemediationAvailable() bool {
	if o == nil || IsNil(o.ExpireWhenRemediationAvailable) {
		var ret bool
		return ret
	}
	return *o.ExpireWhenRemediationAvailable
}

// GetExpireWhenRemediationAvailableOk returns a tuple with the ExpireWhenRemediationAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWaiverOptionsDTO) GetExpireWhenRemediationAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.ExpireWhenRemediationAvailable) {
		return nil, false
	}
	return o.ExpireWhenRemediationAvailable, true
}

// HasExpireWhenRemediationAvailable returns a boolean if a field has been set.
func (o *ApiWaiverOptionsDTO) HasExpireWhenRemediationAvailable() bool {
	if o != nil && !IsNil(o.ExpireWhenRemediationAvailable) {
		return true
	}

	return false
}

// SetExpireWhenRemediationAvailable gets a reference to the given bool and assigns it to the ExpireWhenRemediationAvailable field.
func (o *ApiWaiverOptionsDTO) SetExpireWhenRemediationAvailable(v bool) {
	o.ExpireWhenRemediationAvailable = &v
}

// GetExpiryTime returns the ExpiryTime field value if set, zero value otherwise.
func (o *ApiWaiverOptionsDTO) GetExpiryTime() time.Time {
	if o == nil || IsNil(o.ExpiryTime) {
		var ret time.Time
		return ret
	}
	return *o.ExpiryTime
}

// GetExpiryTimeOk returns a tuple with the ExpiryTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWaiverOptionsDTO) GetExpiryTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ExpiryTime) {
		return nil, false
	}
	return o.ExpiryTime, true
}

// HasExpiryTime returns a boolean if a field has been set.
func (o *ApiWaiverOptionsDTO) HasExpiryTime() bool {
	if o != nil && !IsNil(o.ExpiryTime) {
		return true
	}

	return false
}

// SetExpiryTime gets a reference to the given time.Time and assigns it to the ExpiryTime field.
func (o *ApiWaiverOptionsDTO) SetExpiryTime(v time.Time) {
	o.ExpiryTime = &v
}

// GetMatcherStrategy returns the MatcherStrategy field value
func (o *ApiWaiverOptionsDTO) GetMatcherStrategy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MatcherStrategy
}

// GetMatcherStrategyOk returns a tuple with the MatcherStrategy field value
// and a boolean to check if the value has been set.
func (o *ApiWaiverOptionsDTO) GetMatcherStrategyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MatcherStrategy, true
}

// SetMatcherStrategy sets field value
func (o *ApiWaiverOptionsDTO) SetMatcherStrategy(v string) {
	o.MatcherStrategy = v
}

// GetWaiverReasonId returns the WaiverReasonId field value if set, zero value otherwise.
func (o *ApiWaiverOptionsDTO) GetWaiverReasonId() string {
	if o == nil || IsNil(o.WaiverReasonId) {
		var ret string
		return ret
	}
	return *o.WaiverReasonId
}

// GetWaiverReasonIdOk returns a tuple with the WaiverReasonId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWaiverOptionsDTO) GetWaiverReasonIdOk() (*string, bool) {
	if o == nil || IsNil(o.WaiverReasonId) {
		return nil, false
	}
	return o.WaiverReasonId, true
}

// HasWaiverReasonId returns a boolean if a field has been set.
func (o *ApiWaiverOptionsDTO) HasWaiverReasonId() bool {
	if o != nil && !IsNil(o.WaiverReasonId) {
		return true
	}

	return false
}

// SetWaiverReasonId gets a reference to the given string and assigns it to the WaiverReasonId field.
func (o *ApiWaiverOptionsDTO) SetWaiverReasonId(v string) {
	o.WaiverReasonId = &v
}

func (o ApiWaiverOptionsDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiWaiverOptionsDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["comment"] = o.Comment
	if !IsNil(o.ExpireWhenRemediationAvailable) {
		toSerialize["expireWhenRemediationAvailable"] = o.ExpireWhenRemediationAvailable
	}
	if !IsNil(o.ExpiryTime) {
		toSerialize["expiryTime"] = o.ExpiryTime
	}
	toSerialize["matcherStrategy"] = o.MatcherStrategy
	if !IsNil(o.WaiverReasonId) {
		toSerialize["waiverReasonId"] = o.WaiverReasonId
	}
	return toSerialize, nil
}

func (o *ApiWaiverOptionsDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"comment",
		"matcherStrategy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiWaiverOptionsDTO := _ApiWaiverOptionsDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiWaiverOptionsDTO)

	if err != nil {
		return err
	}

	*o = ApiWaiverOptionsDTO(varApiWaiverOptionsDTO)

	return err
}

type NullableApiWaiverOptionsDTO struct {
	value *ApiWaiverOptionsDTO
	isSet bool
}

func (v NullableApiWaiverOptionsDTO) Get() *ApiWaiverOptionsDTO {
	return v.value
}

func (v *NullableApiWaiverOptionsDTO) Set(val *ApiWaiverOptionsDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableApiWaiverOptionsDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableApiWaiverOptionsDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiWaiverOptionsDTO(val *ApiWaiverOptionsDTO) *NullableApiWaiverOptionsDTO {
	return &NullableApiWaiverOptionsDTO{value: val, isSet: true}
}

func (v NullableApiWaiverOptionsDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiWaiverOptionsDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


