/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.203.0-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the ApiCiConfigurationResponseDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCiConfigurationResponseDto{}

// ApiCiConfigurationResponseDto struct for ApiCiConfigurationResponseDto
type ApiCiConfigurationResponseDto struct {
	Data *ApiCiConfigurationDto `json:"data,omitempty"`
	Source *map[string]string `json:"source,omitempty"`
}

// NewApiCiConfigurationResponseDto instantiates a new ApiCiConfigurationResponseDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCiConfigurationResponseDto() *ApiCiConfigurationResponseDto {
	this := ApiCiConfigurationResponseDto{}
	return &this
}

// NewApiCiConfigurationResponseDtoWithDefaults instantiates a new ApiCiConfigurationResponseDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCiConfigurationResponseDtoWithDefaults() *ApiCiConfigurationResponseDto {
	this := ApiCiConfigurationResponseDto{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ApiCiConfigurationResponseDto) GetData() ApiCiConfigurationDto {
	if o == nil || IsNil(o.Data) {
		var ret ApiCiConfigurationDto
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCiConfigurationResponseDto) GetDataOk() (*ApiCiConfigurationDto, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ApiCiConfigurationResponseDto) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ApiCiConfigurationDto and assigns it to the Data field.
func (o *ApiCiConfigurationResponseDto) SetData(v ApiCiConfigurationDto) {
	o.Data = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *ApiCiConfigurationResponseDto) GetSource() map[string]string {
	if o == nil || IsNil(o.Source) {
		var ret map[string]string
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCiConfigurationResponseDto) GetSourceOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *ApiCiConfigurationResponseDto) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given map[string]string and assigns it to the Source field.
func (o *ApiCiConfigurationResponseDto) SetSource(v map[string]string) {
	o.Source = &v
}

func (o ApiCiConfigurationResponseDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCiConfigurationResponseDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	return toSerialize, nil
}

type NullableApiCiConfigurationResponseDto struct {
	value *ApiCiConfigurationResponseDto
	isSet bool
}

func (v NullableApiCiConfigurationResponseDto) Get() *ApiCiConfigurationResponseDto {
	return v.value
}

func (v *NullableApiCiConfigurationResponseDto) Set(val *ApiCiConfigurationResponseDto) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCiConfigurationResponseDto) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCiConfigurationResponseDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCiConfigurationResponseDto(val *ApiCiConfigurationResponseDto) *NullableApiCiConfigurationResponseDto {
	return &NullableApiCiConfigurationResponseDto{value: val, isSet: true}
}

func (v NullableApiCiConfigurationResponseDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCiConfigurationResponseDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


