/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.192.0-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the ApiCrowdConfigurationDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCrowdConfigurationDTO{}

// ApiCrowdConfigurationDTO struct for ApiCrowdConfigurationDTO
type ApiCrowdConfigurationDTO struct {
	ApplicationName *string `json:"applicationName,omitempty"`
	ApplicationPassword []string `json:"applicationPassword,omitempty"`
	ServerUrl *string `json:"serverUrl,omitempty"`
}

// NewApiCrowdConfigurationDTO instantiates a new ApiCrowdConfigurationDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCrowdConfigurationDTO() *ApiCrowdConfigurationDTO {
	this := ApiCrowdConfigurationDTO{}
	return &this
}

// NewApiCrowdConfigurationDTOWithDefaults instantiates a new ApiCrowdConfigurationDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCrowdConfigurationDTOWithDefaults() *ApiCrowdConfigurationDTO {
	this := ApiCrowdConfigurationDTO{}
	return &this
}

// GetApplicationName returns the ApplicationName field value if set, zero value otherwise.
func (o *ApiCrowdConfigurationDTO) GetApplicationName() string {
	if o == nil || IsNil(o.ApplicationName) {
		var ret string
		return ret
	}
	return *o.ApplicationName
}

// GetApplicationNameOk returns a tuple with the ApplicationName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCrowdConfigurationDTO) GetApplicationNameOk() (*string, bool) {
	if o == nil || IsNil(o.ApplicationName) {
		return nil, false
	}
	return o.ApplicationName, true
}

// HasApplicationName returns a boolean if a field has been set.
func (o *ApiCrowdConfigurationDTO) HasApplicationName() bool {
	if o != nil && !IsNil(o.ApplicationName) {
		return true
	}

	return false
}

// SetApplicationName gets a reference to the given string and assigns it to the ApplicationName field.
func (o *ApiCrowdConfigurationDTO) SetApplicationName(v string) {
	o.ApplicationName = &v
}

// GetApplicationPassword returns the ApplicationPassword field value if set, zero value otherwise.
func (o *ApiCrowdConfigurationDTO) GetApplicationPassword() []string {
	if o == nil || IsNil(o.ApplicationPassword) {
		var ret []string
		return ret
	}
	return o.ApplicationPassword
}

// GetApplicationPasswordOk returns a tuple with the ApplicationPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCrowdConfigurationDTO) GetApplicationPasswordOk() ([]string, bool) {
	if o == nil || IsNil(o.ApplicationPassword) {
		return nil, false
	}
	return o.ApplicationPassword, true
}

// HasApplicationPassword returns a boolean if a field has been set.
func (o *ApiCrowdConfigurationDTO) HasApplicationPassword() bool {
	if o != nil && !IsNil(o.ApplicationPassword) {
		return true
	}

	return false
}

// SetApplicationPassword gets a reference to the given []string and assigns it to the ApplicationPassword field.
func (o *ApiCrowdConfigurationDTO) SetApplicationPassword(v []string) {
	o.ApplicationPassword = v
}

// GetServerUrl returns the ServerUrl field value if set, zero value otherwise.
func (o *ApiCrowdConfigurationDTO) GetServerUrl() string {
	if o == nil || IsNil(o.ServerUrl) {
		var ret string
		return ret
	}
	return *o.ServerUrl
}

// GetServerUrlOk returns a tuple with the ServerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCrowdConfigurationDTO) GetServerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ServerUrl) {
		return nil, false
	}
	return o.ServerUrl, true
}

// HasServerUrl returns a boolean if a field has been set.
func (o *ApiCrowdConfigurationDTO) HasServerUrl() bool {
	if o != nil && !IsNil(o.ServerUrl) {
		return true
	}

	return false
}

// SetServerUrl gets a reference to the given string and assigns it to the ServerUrl field.
func (o *ApiCrowdConfigurationDTO) SetServerUrl(v string) {
	o.ServerUrl = &v
}

func (o ApiCrowdConfigurationDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCrowdConfigurationDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplicationName) {
		toSerialize["applicationName"] = o.ApplicationName
	}
	if !IsNil(o.ApplicationPassword) {
		toSerialize["applicationPassword"] = o.ApplicationPassword
	}
	if !IsNil(o.ServerUrl) {
		toSerialize["serverUrl"] = o.ServerUrl
	}
	return toSerialize, nil
}

type NullableApiCrowdConfigurationDTO struct {
	value *ApiCrowdConfigurationDTO
	isSet bool
}

func (v NullableApiCrowdConfigurationDTO) Get() *ApiCrowdConfigurationDTO {
	return v.value
}

func (v *NullableApiCrowdConfigurationDTO) Set(val *ApiCrowdConfigurationDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCrowdConfigurationDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCrowdConfigurationDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCrowdConfigurationDTO(val *ApiCrowdConfigurationDTO) *NullableApiCrowdConfigurationDTO {
	return &NullableApiCrowdConfigurationDTO{value: val, isSet: true}
}

func (v NullableApiCrowdConfigurationDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCrowdConfigurationDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


