/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.195.0-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the ComponentLocator type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ComponentLocator{}

// ComponentLocator Component details about the vulnerable component. Either hash or package URL must be provided
type ComponentLocator struct {
	// Component hash
	Hash *string `json:"hash,omitempty"`
	// Component package URL
	PackageUrl *string `json:"packageUrl,omitempty"`
}

// NewComponentLocator instantiates a new ComponentLocator object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewComponentLocator() *ComponentLocator {
	this := ComponentLocator{}
	return &this
}

// NewComponentLocatorWithDefaults instantiates a new ComponentLocator object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewComponentLocatorWithDefaults() *ComponentLocator {
	this := ComponentLocator{}
	return &this
}

// GetHash returns the Hash field value if set, zero value otherwise.
func (o *ComponentLocator) GetHash() string {
	if o == nil || IsNil(o.Hash) {
		var ret string
		return ret
	}
	return *o.Hash
}

// GetHashOk returns a tuple with the Hash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentLocator) GetHashOk() (*string, bool) {
	if o == nil || IsNil(o.Hash) {
		return nil, false
	}
	return o.Hash, true
}

// HasHash returns a boolean if a field has been set.
func (o *ComponentLocator) HasHash() bool {
	if o != nil && !IsNil(o.Hash) {
		return true
	}

	return false
}

// SetHash gets a reference to the given string and assigns it to the Hash field.
func (o *ComponentLocator) SetHash(v string) {
	o.Hash = &v
}

// GetPackageUrl returns the PackageUrl field value if set, zero value otherwise.
func (o *ComponentLocator) GetPackageUrl() string {
	if o == nil || IsNil(o.PackageUrl) {
		var ret string
		return ret
	}
	return *o.PackageUrl
}

// GetPackageUrlOk returns a tuple with the PackageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ComponentLocator) GetPackageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PackageUrl) {
		return nil, false
	}
	return o.PackageUrl, true
}

// HasPackageUrl returns a boolean if a field has been set.
func (o *ComponentLocator) HasPackageUrl() bool {
	if o != nil && !IsNil(o.PackageUrl) {
		return true
	}

	return false
}

// SetPackageUrl gets a reference to the given string and assigns it to the PackageUrl field.
func (o *ComponentLocator) SetPackageUrl(v string) {
	o.PackageUrl = &v
}

func (o ComponentLocator) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ComponentLocator) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hash) {
		toSerialize["hash"] = o.Hash
	}
	if !IsNil(o.PackageUrl) {
		toSerialize["packageUrl"] = o.PackageUrl
	}
	return toSerialize, nil
}

type NullableComponentLocator struct {
	value *ComponentLocator
	isSet bool
}

func (v NullableComponentLocator) Get() *ComponentLocator {
	return v.value
}

func (v *NullableComponentLocator) Set(val *ComponentLocator) {
	v.value = val
	v.isSet = true
}

func (v NullableComponentLocator) IsSet() bool {
	return v.isSet
}

func (v *NullableComponentLocator) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableComponentLocator(val *ComponentLocator) *NullableComponentLocator {
	return &NullableComponentLocator{value: val, isSet: true}
}

func (v NullableComponentLocator) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableComponentLocator) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


