/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.196.0-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the ReferenceLinkDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReferenceLinkDTO{}

// ReferenceLinkDTO struct for ReferenceLinkDTO
type ReferenceLinkDTO struct {
	ReferenceType *string `json:"referenceType,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewReferenceLinkDTO instantiates a new ReferenceLinkDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReferenceLinkDTO() *ReferenceLinkDTO {
	this := ReferenceLinkDTO{}
	return &this
}

// NewReferenceLinkDTOWithDefaults instantiates a new ReferenceLinkDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReferenceLinkDTOWithDefaults() *ReferenceLinkDTO {
	this := ReferenceLinkDTO{}
	return &this
}

// GetReferenceType returns the ReferenceType field value if set, zero value otherwise.
func (o *ReferenceLinkDTO) GetReferenceType() string {
	if o == nil || IsNil(o.ReferenceType) {
		var ret string
		return ret
	}
	return *o.ReferenceType
}

// GetReferenceTypeOk returns a tuple with the ReferenceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceLinkDTO) GetReferenceTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ReferenceType) {
		return nil, false
	}
	return o.ReferenceType, true
}

// HasReferenceType returns a boolean if a field has been set.
func (o *ReferenceLinkDTO) HasReferenceType() bool {
	if o != nil && !IsNil(o.ReferenceType) {
		return true
	}

	return false
}

// SetReferenceType gets a reference to the given string and assigns it to the ReferenceType field.
func (o *ReferenceLinkDTO) SetReferenceType(v string) {
	o.ReferenceType = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ReferenceLinkDTO) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReferenceLinkDTO) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ReferenceLinkDTO) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ReferenceLinkDTO) SetUrl(v string) {
	o.Url = &v
}

func (o ReferenceLinkDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReferenceLinkDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ReferenceType) {
		toSerialize["referenceType"] = o.ReferenceType
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableReferenceLinkDTO struct {
	value *ReferenceLinkDTO
	isSet bool
}

func (v NullableReferenceLinkDTO) Get() *ReferenceLinkDTO {
	return v.value
}

func (v *NullableReferenceLinkDTO) Set(val *ReferenceLinkDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableReferenceLinkDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableReferenceLinkDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReferenceLinkDTO(val *ReferenceLinkDTO) *NullableReferenceLinkDTO {
	return &NullableReferenceLinkDTO{value: val, isSet: true}
}

func (v NullableReferenceLinkDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReferenceLinkDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


