/*
Sonatype IQ Server

This documents the available APIs into [Sonatype IQ Server](https://www.sonatype.com/products/open-source-security-dependency-management).

API version: 165
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the CweId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CweId{}

// CweId struct for CweId
type CweId struct {
	Id *string `json:"id,omitempty"`
	Uri *string `json:"uri,omitempty"`
}

// NewCweId instantiates a new CweId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCweId() *CweId {
	this := CweId{}
	return &this
}

// NewCweIdWithDefaults instantiates a new CweId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCweIdWithDefaults() *CweId {
	this := CweId{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CweId) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CweId) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CweId) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CweId) SetId(v string) {
	o.Id = &v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *CweId) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CweId) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *CweId) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *CweId) SetUri(v string) {
	o.Uri = &v
}

func (o CweId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CweId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}
	return toSerialize, nil
}

type NullableCweId struct {
	value *CweId
	isSet bool
}

func (v NullableCweId) Get() *CweId {
	return v.value
}

func (v *NullableCweId) Set(val *CweId) {
	v.value = val
	v.isSet = true
}

func (v NullableCweId) IsSet() bool {
	return v.isSet
}

func (v *NullableCweId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCweId(val *CweId) *NullableCweId {
	return &NullableCweId{value: val, isSet: true}
}

func (v NullableCweId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCweId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


