/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.198.0-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the ApiRoleWithMembersByOwnerDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiRoleWithMembersByOwnerDTO{}

// ApiRoleWithMembersByOwnerDTO struct for ApiRoleWithMembersByOwnerDTO
type ApiRoleWithMembersByOwnerDTO struct {
	MembersByOwner []ApiMembersByOwnerDTO `json:"membersByOwner,omitempty"`
	RoleDescription *string `json:"roleDescription,omitempty"`
	RoleId *string `json:"roleId,omitempty"`
	RoleName *string `json:"roleName,omitempty"`
}

// NewApiRoleWithMembersByOwnerDTO instantiates a new ApiRoleWithMembersByOwnerDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiRoleWithMembersByOwnerDTO() *ApiRoleWithMembersByOwnerDTO {
	this := ApiRoleWithMembersByOwnerDTO{}
	return &this
}

// NewApiRoleWithMembersByOwnerDTOWithDefaults instantiates a new ApiRoleWithMembersByOwnerDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiRoleWithMembersByOwnerDTOWithDefaults() *ApiRoleWithMembersByOwnerDTO {
	this := ApiRoleWithMembersByOwnerDTO{}
	return &this
}

// GetMembersByOwner returns the MembersByOwner field value if set, zero value otherwise.
func (o *ApiRoleWithMembersByOwnerDTO) GetMembersByOwner() []ApiMembersByOwnerDTO {
	if o == nil || IsNil(o.MembersByOwner) {
		var ret []ApiMembersByOwnerDTO
		return ret
	}
	return o.MembersByOwner
}

// GetMembersByOwnerOk returns a tuple with the MembersByOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRoleWithMembersByOwnerDTO) GetMembersByOwnerOk() ([]ApiMembersByOwnerDTO, bool) {
	if o == nil || IsNil(o.MembersByOwner) {
		return nil, false
	}
	return o.MembersByOwner, true
}

// HasMembersByOwner returns a boolean if a field has been set.
func (o *ApiRoleWithMembersByOwnerDTO) HasMembersByOwner() bool {
	if o != nil && !IsNil(o.MembersByOwner) {
		return true
	}

	return false
}

// SetMembersByOwner gets a reference to the given []ApiMembersByOwnerDTO and assigns it to the MembersByOwner field.
func (o *ApiRoleWithMembersByOwnerDTO) SetMembersByOwner(v []ApiMembersByOwnerDTO) {
	o.MembersByOwner = v
}

// GetRoleDescription returns the RoleDescription field value if set, zero value otherwise.
func (o *ApiRoleWithMembersByOwnerDTO) GetRoleDescription() string {
	if o == nil || IsNil(o.RoleDescription) {
		var ret string
		return ret
	}
	return *o.RoleDescription
}

// GetRoleDescriptionOk returns a tuple with the RoleDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRoleWithMembersByOwnerDTO) GetRoleDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.RoleDescription) {
		return nil, false
	}
	return o.RoleDescription, true
}

// HasRoleDescription returns a boolean if a field has been set.
func (o *ApiRoleWithMembersByOwnerDTO) HasRoleDescription() bool {
	if o != nil && !IsNil(o.RoleDescription) {
		return true
	}

	return false
}

// SetRoleDescription gets a reference to the given string and assigns it to the RoleDescription field.
func (o *ApiRoleWithMembersByOwnerDTO) SetRoleDescription(v string) {
	o.RoleDescription = &v
}

// GetRoleId returns the RoleId field value if set, zero value otherwise.
func (o *ApiRoleWithMembersByOwnerDTO) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRoleWithMembersByOwnerDTO) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

// HasRoleId returns a boolean if a field has been set.
func (o *ApiRoleWithMembersByOwnerDTO) HasRoleId() bool {
	if o != nil && !IsNil(o.RoleId) {
		return true
	}

	return false
}

// SetRoleId gets a reference to the given string and assigns it to the RoleId field.
func (o *ApiRoleWithMembersByOwnerDTO) SetRoleId(v string) {
	o.RoleId = &v
}

// GetRoleName returns the RoleName field value if set, zero value otherwise.
func (o *ApiRoleWithMembersByOwnerDTO) GetRoleName() string {
	if o == nil || IsNil(o.RoleName) {
		var ret string
		return ret
	}
	return *o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiRoleWithMembersByOwnerDTO) GetRoleNameOk() (*string, bool) {
	if o == nil || IsNil(o.RoleName) {
		return nil, false
	}
	return o.RoleName, true
}

// HasRoleName returns a boolean if a field has been set.
func (o *ApiRoleWithMembersByOwnerDTO) HasRoleName() bool {
	if o != nil && !IsNil(o.RoleName) {
		return true
	}

	return false
}

// SetRoleName gets a reference to the given string and assigns it to the RoleName field.
func (o *ApiRoleWithMembersByOwnerDTO) SetRoleName(v string) {
	o.RoleName = &v
}

func (o ApiRoleWithMembersByOwnerDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiRoleWithMembersByOwnerDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MembersByOwner) {
		toSerialize["membersByOwner"] = o.MembersByOwner
	}
	if !IsNil(o.RoleDescription) {
		toSerialize["roleDescription"] = o.RoleDescription
	}
	if !IsNil(o.RoleId) {
		toSerialize["roleId"] = o.RoleId
	}
	if !IsNil(o.RoleName) {
		toSerialize["roleName"] = o.RoleName
	}
	return toSerialize, nil
}

type NullableApiRoleWithMembersByOwnerDTO struct {
	value *ApiRoleWithMembersByOwnerDTO
	isSet bool
}

func (v NullableApiRoleWithMembersByOwnerDTO) Get() *ApiRoleWithMembersByOwnerDTO {
	return v.value
}

func (v *NullableApiRoleWithMembersByOwnerDTO) Set(val *ApiRoleWithMembersByOwnerDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableApiRoleWithMembersByOwnerDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableApiRoleWithMembersByOwnerDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiRoleWithMembersByOwnerDTO(val *ApiRoleWithMembersByOwnerDTO) *NullableApiRoleWithMembersByOwnerDTO {
	return &NullableApiRoleWithMembersByOwnerDTO{value: val, isSet: true}
}

func (v NullableApiRoleWithMembersByOwnerDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiRoleWithMembersByOwnerDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


