/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.201.0-02
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the OidcConfigurationDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OidcConfigurationDTO{}

// OidcConfigurationDTO struct for OidcConfigurationDTO
type OidcConfigurationDTO struct {
	AuthorizationCustomParamsJson *string `json:"authorizationCustomParamsJson,omitempty"`
	ClientId *string `json:"clientId,omitempty"`
	ClientSecret *string `json:"clientSecret,omitempty"`
	IdpAuthorizationUrl *string `json:"idpAuthorizationUrl,omitempty"`
	IdpIssuer *string `json:"idpIssuer,omitempty"`
	IdpTokenUrl *string `json:"idpTokenUrl,omitempty"`
	TokenRequestCustomParamsJson *string `json:"tokenRequestCustomParamsJson,omitempty"`
}

// NewOidcConfigurationDTO instantiates a new OidcConfigurationDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOidcConfigurationDTO() *OidcConfigurationDTO {
	this := OidcConfigurationDTO{}
	return &this
}

// NewOidcConfigurationDTOWithDefaults instantiates a new OidcConfigurationDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOidcConfigurationDTOWithDefaults() *OidcConfigurationDTO {
	this := OidcConfigurationDTO{}
	return &this
}

// GetAuthorizationCustomParamsJson returns the AuthorizationCustomParamsJson field value if set, zero value otherwise.
func (o *OidcConfigurationDTO) GetAuthorizationCustomParamsJson() string {
	if o == nil || IsNil(o.AuthorizationCustomParamsJson) {
		var ret string
		return ret
	}
	return *o.AuthorizationCustomParamsJson
}

// GetAuthorizationCustomParamsJsonOk returns a tuple with the AuthorizationCustomParamsJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OidcConfigurationDTO) GetAuthorizationCustomParamsJsonOk() (*string, bool) {
	if o == nil || IsNil(o.AuthorizationCustomParamsJson) {
		return nil, false
	}
	return o.AuthorizationCustomParamsJson, true
}

// HasAuthorizationCustomParamsJson returns a boolean if a field has been set.
func (o *OidcConfigurationDTO) HasAuthorizationCustomParamsJson() bool {
	if o != nil && !IsNil(o.AuthorizationCustomParamsJson) {
		return true
	}

	return false
}

// SetAuthorizationCustomParamsJson gets a reference to the given string and assigns it to the AuthorizationCustomParamsJson field.
func (o *OidcConfigurationDTO) SetAuthorizationCustomParamsJson(v string) {
	o.AuthorizationCustomParamsJson = &v
}

// GetClientId returns the ClientId field value if set, zero value otherwise.
func (o *OidcConfigurationDTO) GetClientId() string {
	if o == nil || IsNil(o.ClientId) {
		var ret string
		return ret
	}
	return *o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OidcConfigurationDTO) GetClientIdOk() (*string, bool) {
	if o == nil || IsNil(o.ClientId) {
		return nil, false
	}
	return o.ClientId, true
}

// HasClientId returns a boolean if a field has been set.
func (o *OidcConfigurationDTO) HasClientId() bool {
	if o != nil && !IsNil(o.ClientId) {
		return true
	}

	return false
}

// SetClientId gets a reference to the given string and assigns it to the ClientId field.
func (o *OidcConfigurationDTO) SetClientId(v string) {
	o.ClientId = &v
}

// GetClientSecret returns the ClientSecret field value if set, zero value otherwise.
func (o *OidcConfigurationDTO) GetClientSecret() string {
	if o == nil || IsNil(o.ClientSecret) {
		var ret string
		return ret
	}
	return *o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OidcConfigurationDTO) GetClientSecretOk() (*string, bool) {
	if o == nil || IsNil(o.ClientSecret) {
		return nil, false
	}
	return o.ClientSecret, true
}

// HasClientSecret returns a boolean if a field has been set.
func (o *OidcConfigurationDTO) HasClientSecret() bool {
	if o != nil && !IsNil(o.ClientSecret) {
		return true
	}

	return false
}

// SetClientSecret gets a reference to the given string and assigns it to the ClientSecret field.
func (o *OidcConfigurationDTO) SetClientSecret(v string) {
	o.ClientSecret = &v
}

// GetIdpAuthorizationUrl returns the IdpAuthorizationUrl field value if set, zero value otherwise.
func (o *OidcConfigurationDTO) GetIdpAuthorizationUrl() string {
	if o == nil || IsNil(o.IdpAuthorizationUrl) {
		var ret string
		return ret
	}
	return *o.IdpAuthorizationUrl
}

// GetIdpAuthorizationUrlOk returns a tuple with the IdpAuthorizationUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OidcConfigurationDTO) GetIdpAuthorizationUrlOk() (*string, bool) {
	if o == nil || IsNil(o.IdpAuthorizationUrl) {
		return nil, false
	}
	return o.IdpAuthorizationUrl, true
}

// HasIdpAuthorizationUrl returns a boolean if a field has been set.
func (o *OidcConfigurationDTO) HasIdpAuthorizationUrl() bool {
	if o != nil && !IsNil(o.IdpAuthorizationUrl) {
		return true
	}

	return false
}

// SetIdpAuthorizationUrl gets a reference to the given string and assigns it to the IdpAuthorizationUrl field.
func (o *OidcConfigurationDTO) SetIdpAuthorizationUrl(v string) {
	o.IdpAuthorizationUrl = &v
}

// GetIdpIssuer returns the IdpIssuer field value if set, zero value otherwise.
func (o *OidcConfigurationDTO) GetIdpIssuer() string {
	if o == nil || IsNil(o.IdpIssuer) {
		var ret string
		return ret
	}
	return *o.IdpIssuer
}

// GetIdpIssuerOk returns a tuple with the IdpIssuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OidcConfigurationDTO) GetIdpIssuerOk() (*string, bool) {
	if o == nil || IsNil(o.IdpIssuer) {
		return nil, false
	}
	return o.IdpIssuer, true
}

// HasIdpIssuer returns a boolean if a field has been set.
func (o *OidcConfigurationDTO) HasIdpIssuer() bool {
	if o != nil && !IsNil(o.IdpIssuer) {
		return true
	}

	return false
}

// SetIdpIssuer gets a reference to the given string and assigns it to the IdpIssuer field.
func (o *OidcConfigurationDTO) SetIdpIssuer(v string) {
	o.IdpIssuer = &v
}

// GetIdpTokenUrl returns the IdpTokenUrl field value if set, zero value otherwise.
func (o *OidcConfigurationDTO) GetIdpTokenUrl() string {
	if o == nil || IsNil(o.IdpTokenUrl) {
		var ret string
		return ret
	}
	return *o.IdpTokenUrl
}

// GetIdpTokenUrlOk returns a tuple with the IdpTokenUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OidcConfigurationDTO) GetIdpTokenUrlOk() (*string, bool) {
	if o == nil || IsNil(o.IdpTokenUrl) {
		return nil, false
	}
	return o.IdpTokenUrl, true
}

// HasIdpTokenUrl returns a boolean if a field has been set.
func (o *OidcConfigurationDTO) HasIdpTokenUrl() bool {
	if o != nil && !IsNil(o.IdpTokenUrl) {
		return true
	}

	return false
}

// SetIdpTokenUrl gets a reference to the given string and assigns it to the IdpTokenUrl field.
func (o *OidcConfigurationDTO) SetIdpTokenUrl(v string) {
	o.IdpTokenUrl = &v
}

// GetTokenRequestCustomParamsJson returns the TokenRequestCustomParamsJson field value if set, zero value otherwise.
func (o *OidcConfigurationDTO) GetTokenRequestCustomParamsJson() string {
	if o == nil || IsNil(o.TokenRequestCustomParamsJson) {
		var ret string
		return ret
	}
	return *o.TokenRequestCustomParamsJson
}

// GetTokenRequestCustomParamsJsonOk returns a tuple with the TokenRequestCustomParamsJson field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OidcConfigurationDTO) GetTokenRequestCustomParamsJsonOk() (*string, bool) {
	if o == nil || IsNil(o.TokenRequestCustomParamsJson) {
		return nil, false
	}
	return o.TokenRequestCustomParamsJson, true
}

// HasTokenRequestCustomParamsJson returns a boolean if a field has been set.
func (o *OidcConfigurationDTO) HasTokenRequestCustomParamsJson() bool {
	if o != nil && !IsNil(o.TokenRequestCustomParamsJson) {
		return true
	}

	return false
}

// SetTokenRequestCustomParamsJson gets a reference to the given string and assigns it to the TokenRequestCustomParamsJson field.
func (o *OidcConfigurationDTO) SetTokenRequestCustomParamsJson(v string) {
	o.TokenRequestCustomParamsJson = &v
}

func (o OidcConfigurationDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OidcConfigurationDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AuthorizationCustomParamsJson) {
		toSerialize["authorizationCustomParamsJson"] = o.AuthorizationCustomParamsJson
	}
	if !IsNil(o.ClientId) {
		toSerialize["clientId"] = o.ClientId
	}
	if !IsNil(o.ClientSecret) {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	if !IsNil(o.IdpAuthorizationUrl) {
		toSerialize["idpAuthorizationUrl"] = o.IdpAuthorizationUrl
	}
	if !IsNil(o.IdpIssuer) {
		toSerialize["idpIssuer"] = o.IdpIssuer
	}
	if !IsNil(o.IdpTokenUrl) {
		toSerialize["idpTokenUrl"] = o.IdpTokenUrl
	}
	if !IsNil(o.TokenRequestCustomParamsJson) {
		toSerialize["tokenRequestCustomParamsJson"] = o.TokenRequestCustomParamsJson
	}
	return toSerialize, nil
}

type NullableOidcConfigurationDTO struct {
	value *OidcConfigurationDTO
	isSet bool
}

func (v NullableOidcConfigurationDTO) Get() *OidcConfigurationDTO {
	return v.value
}

func (v *NullableOidcConfigurationDTO) Set(val *OidcConfigurationDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableOidcConfigurationDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableOidcConfigurationDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOidcConfigurationDTO(val *OidcConfigurationDTO) *NullableOidcConfigurationDTO {
	return &NullableOidcConfigurationDTO{value: val, isSet: true}
}

func (v NullableOidcConfigurationDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOidcConfigurationDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


