/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.204.2-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the ApiMemberWithDetailsDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMemberWithDetailsDTO{}

// ApiMemberWithDetailsDTO struct for ApiMemberWithDetailsDTO
type ApiMemberWithDetailsDTO struct {
	DisplayName *string `json:"displayName,omitempty"`
	Email *string `json:"email,omitempty"`
	InternalName *string `json:"internalName,omitempty"`
	Realm *string `json:"realm,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewApiMemberWithDetailsDTO instantiates a new ApiMemberWithDetailsDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMemberWithDetailsDTO() *ApiMemberWithDetailsDTO {
	this := ApiMemberWithDetailsDTO{}
	return &this
}

// NewApiMemberWithDetailsDTOWithDefaults instantiates a new ApiMemberWithDetailsDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMemberWithDetailsDTOWithDefaults() *ApiMemberWithDetailsDTO {
	this := ApiMemberWithDetailsDTO{}
	return &this
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *ApiMemberWithDetailsDTO) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMemberWithDetailsDTO) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *ApiMemberWithDetailsDTO) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *ApiMemberWithDetailsDTO) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *ApiMemberWithDetailsDTO) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMemberWithDetailsDTO) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *ApiMemberWithDetailsDTO) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *ApiMemberWithDetailsDTO) SetEmail(v string) {
	o.Email = &v
}

// GetInternalName returns the InternalName field value if set, zero value otherwise.
func (o *ApiMemberWithDetailsDTO) GetInternalName() string {
	if o == nil || IsNil(o.InternalName) {
		var ret string
		return ret
	}
	return *o.InternalName
}

// GetInternalNameOk returns a tuple with the InternalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMemberWithDetailsDTO) GetInternalNameOk() (*string, bool) {
	if o == nil || IsNil(o.InternalName) {
		return nil, false
	}
	return o.InternalName, true
}

// HasInternalName returns a boolean if a field has been set.
func (o *ApiMemberWithDetailsDTO) HasInternalName() bool {
	if o != nil && !IsNil(o.InternalName) {
		return true
	}

	return false
}

// SetInternalName gets a reference to the given string and assigns it to the InternalName field.
func (o *ApiMemberWithDetailsDTO) SetInternalName(v string) {
	o.InternalName = &v
}

// GetRealm returns the Realm field value if set, zero value otherwise.
func (o *ApiMemberWithDetailsDTO) GetRealm() string {
	if o == nil || IsNil(o.Realm) {
		var ret string
		return ret
	}
	return *o.Realm
}

// GetRealmOk returns a tuple with the Realm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMemberWithDetailsDTO) GetRealmOk() (*string, bool) {
	if o == nil || IsNil(o.Realm) {
		return nil, false
	}
	return o.Realm, true
}

// HasRealm returns a boolean if a field has been set.
func (o *ApiMemberWithDetailsDTO) HasRealm() bool {
	if o != nil && !IsNil(o.Realm) {
		return true
	}

	return false
}

// SetRealm gets a reference to the given string and assigns it to the Realm field.
func (o *ApiMemberWithDetailsDTO) SetRealm(v string) {
	o.Realm = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiMemberWithDetailsDTO) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiMemberWithDetailsDTO) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiMemberWithDetailsDTO) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiMemberWithDetailsDTO) SetType(v string) {
	o.Type = &v
}

func (o ApiMemberWithDetailsDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMemberWithDetailsDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.InternalName) {
		toSerialize["internalName"] = o.InternalName
	}
	if !IsNil(o.Realm) {
		toSerialize["realm"] = o.Realm
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableApiMemberWithDetailsDTO struct {
	value *ApiMemberWithDetailsDTO
	isSet bool
}

func (v NullableApiMemberWithDetailsDTO) Get() *ApiMemberWithDetailsDTO {
	return v.value
}

func (v *NullableApiMemberWithDetailsDTO) Set(val *ApiMemberWithDetailsDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMemberWithDetailsDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMemberWithDetailsDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMemberWithDetailsDTO(val *ApiMemberWithDetailsDTO) *NullableApiMemberWithDetailsDTO {
	return &NullableApiMemberWithDetailsDTO{value: val, isSet: true}
}

func (v NullableApiMemberWithDetailsDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMemberWithDetailsDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


