/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.200.0-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the SsoConfigurationDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SsoConfigurationDTO{}

// SsoConfigurationDTO struct for SsoConfigurationDTO
type SsoConfigurationDTO struct {
	Oauth2Configuration *OAuth2ConfigurationDTO `json:"oauth2Configuration,omitempty"`
	OidcConfiguration *OidcConfigurationDTO `json:"oidcConfiguration,omitempty"`
}

// NewSsoConfigurationDTO instantiates a new SsoConfigurationDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSsoConfigurationDTO() *SsoConfigurationDTO {
	this := SsoConfigurationDTO{}
	return &this
}

// NewSsoConfigurationDTOWithDefaults instantiates a new SsoConfigurationDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSsoConfigurationDTOWithDefaults() *SsoConfigurationDTO {
	this := SsoConfigurationDTO{}
	return &this
}

// GetOauth2Configuration returns the Oauth2Configuration field value if set, zero value otherwise.
func (o *SsoConfigurationDTO) GetOauth2Configuration() OAuth2ConfigurationDTO {
	if o == nil || IsNil(o.Oauth2Configuration) {
		var ret OAuth2ConfigurationDTO
		return ret
	}
	return *o.Oauth2Configuration
}

// GetOauth2ConfigurationOk returns a tuple with the Oauth2Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SsoConfigurationDTO) GetOauth2ConfigurationOk() (*OAuth2ConfigurationDTO, bool) {
	if o == nil || IsNil(o.Oauth2Configuration) {
		return nil, false
	}
	return o.Oauth2Configuration, true
}

// HasOauth2Configuration returns a boolean if a field has been set.
func (o *SsoConfigurationDTO) HasOauth2Configuration() bool {
	if o != nil && !IsNil(o.Oauth2Configuration) {
		return true
	}

	return false
}

// SetOauth2Configuration gets a reference to the given OAuth2ConfigurationDTO and assigns it to the Oauth2Configuration field.
func (o *SsoConfigurationDTO) SetOauth2Configuration(v OAuth2ConfigurationDTO) {
	o.Oauth2Configuration = &v
}

// GetOidcConfiguration returns the OidcConfiguration field value if set, zero value otherwise.
func (o *SsoConfigurationDTO) GetOidcConfiguration() OidcConfigurationDTO {
	if o == nil || IsNil(o.OidcConfiguration) {
		var ret OidcConfigurationDTO
		return ret
	}
	return *o.OidcConfiguration
}

// GetOidcConfigurationOk returns a tuple with the OidcConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SsoConfigurationDTO) GetOidcConfigurationOk() (*OidcConfigurationDTO, bool) {
	if o == nil || IsNil(o.OidcConfiguration) {
		return nil, false
	}
	return o.OidcConfiguration, true
}

// HasOidcConfiguration returns a boolean if a field has been set.
func (o *SsoConfigurationDTO) HasOidcConfiguration() bool {
	if o != nil && !IsNil(o.OidcConfiguration) {
		return true
	}

	return false
}

// SetOidcConfiguration gets a reference to the given OidcConfigurationDTO and assigns it to the OidcConfiguration field.
func (o *SsoConfigurationDTO) SetOidcConfiguration(v OidcConfigurationDTO) {
	o.OidcConfiguration = &v
}

func (o SsoConfigurationDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SsoConfigurationDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Oauth2Configuration) {
		toSerialize["oauth2Configuration"] = o.Oauth2Configuration
	}
	if !IsNil(o.OidcConfiguration) {
		toSerialize["oidcConfiguration"] = o.OidcConfiguration
	}
	return toSerialize, nil
}

type NullableSsoConfigurationDTO struct {
	value *SsoConfigurationDTO
	isSet bool
}

func (v NullableSsoConfigurationDTO) Get() *SsoConfigurationDTO {
	return v.value
}

func (v *NullableSsoConfigurationDTO) Set(val *SsoConfigurationDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableSsoConfigurationDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableSsoConfigurationDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSsoConfigurationDTO(val *SsoConfigurationDTO) *NullableSsoConfigurationDTO {
	return &NullableSsoConfigurationDTO{value: val, isSet: true}
}

func (v NullableSsoConfigurationDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSsoConfigurationDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


