/*
Sonatype Lifecycle Public REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.176.0-01
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sonatypeiq

import (
	"encoding/json"
)

// checks if the ApiSbomApplicationsHistoryMetricDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiSbomApplicationsHistoryMetricDTO{}

// ApiSbomApplicationsHistoryMetricDTO struct for ApiSbomApplicationsHistoryMetricDTO
type ApiSbomApplicationsHistoryMetricDTO struct {
	ApplicationsUpdatedLastMonth *int64 `json:"applicationsUpdatedLastMonth,omitempty"`
	ApplicationsUpdatedLastWeek *int64 `json:"applicationsUpdatedLastWeek,omitempty"`
	ApplicationsUpdatedLastYear *int64 `json:"applicationsUpdatedLastYear,omitempty"`
	TotalScannedApplications *int64 `json:"totalScannedApplications,omitempty"`
}

// NewApiSbomApplicationsHistoryMetricDTO instantiates a new ApiSbomApplicationsHistoryMetricDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiSbomApplicationsHistoryMetricDTO() *ApiSbomApplicationsHistoryMetricDTO {
	this := ApiSbomApplicationsHistoryMetricDTO{}
	return &this
}

// NewApiSbomApplicationsHistoryMetricDTOWithDefaults instantiates a new ApiSbomApplicationsHistoryMetricDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiSbomApplicationsHistoryMetricDTOWithDefaults() *ApiSbomApplicationsHistoryMetricDTO {
	this := ApiSbomApplicationsHistoryMetricDTO{}
	return &this
}

// GetApplicationsUpdatedLastMonth returns the ApplicationsUpdatedLastMonth field value if set, zero value otherwise.
func (o *ApiSbomApplicationsHistoryMetricDTO) GetApplicationsUpdatedLastMonth() int64 {
	if o == nil || IsNil(o.ApplicationsUpdatedLastMonth) {
		var ret int64
		return ret
	}
	return *o.ApplicationsUpdatedLastMonth
}

// GetApplicationsUpdatedLastMonthOk returns a tuple with the ApplicationsUpdatedLastMonth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSbomApplicationsHistoryMetricDTO) GetApplicationsUpdatedLastMonthOk() (*int64, bool) {
	if o == nil || IsNil(o.ApplicationsUpdatedLastMonth) {
		return nil, false
	}
	return o.ApplicationsUpdatedLastMonth, true
}

// HasApplicationsUpdatedLastMonth returns a boolean if a field has been set.
func (o *ApiSbomApplicationsHistoryMetricDTO) HasApplicationsUpdatedLastMonth() bool {
	if o != nil && !IsNil(o.ApplicationsUpdatedLastMonth) {
		return true
	}

	return false
}

// SetApplicationsUpdatedLastMonth gets a reference to the given int64 and assigns it to the ApplicationsUpdatedLastMonth field.
func (o *ApiSbomApplicationsHistoryMetricDTO) SetApplicationsUpdatedLastMonth(v int64) {
	o.ApplicationsUpdatedLastMonth = &v
}

// GetApplicationsUpdatedLastWeek returns the ApplicationsUpdatedLastWeek field value if set, zero value otherwise.
func (o *ApiSbomApplicationsHistoryMetricDTO) GetApplicationsUpdatedLastWeek() int64 {
	if o == nil || IsNil(o.ApplicationsUpdatedLastWeek) {
		var ret int64
		return ret
	}
	return *o.ApplicationsUpdatedLastWeek
}

// GetApplicationsUpdatedLastWeekOk returns a tuple with the ApplicationsUpdatedLastWeek field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSbomApplicationsHistoryMetricDTO) GetApplicationsUpdatedLastWeekOk() (*int64, bool) {
	if o == nil || IsNil(o.ApplicationsUpdatedLastWeek) {
		return nil, false
	}
	return o.ApplicationsUpdatedLastWeek, true
}

// HasApplicationsUpdatedLastWeek returns a boolean if a field has been set.
func (o *ApiSbomApplicationsHistoryMetricDTO) HasApplicationsUpdatedLastWeek() bool {
	if o != nil && !IsNil(o.ApplicationsUpdatedLastWeek) {
		return true
	}

	return false
}

// SetApplicationsUpdatedLastWeek gets a reference to the given int64 and assigns it to the ApplicationsUpdatedLastWeek field.
func (o *ApiSbomApplicationsHistoryMetricDTO) SetApplicationsUpdatedLastWeek(v int64) {
	o.ApplicationsUpdatedLastWeek = &v
}

// GetApplicationsUpdatedLastYear returns the ApplicationsUpdatedLastYear field value if set, zero value otherwise.
func (o *ApiSbomApplicationsHistoryMetricDTO) GetApplicationsUpdatedLastYear() int64 {
	if o == nil || IsNil(o.ApplicationsUpdatedLastYear) {
		var ret int64
		return ret
	}
	return *o.ApplicationsUpdatedLastYear
}

// GetApplicationsUpdatedLastYearOk returns a tuple with the ApplicationsUpdatedLastYear field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSbomApplicationsHistoryMetricDTO) GetApplicationsUpdatedLastYearOk() (*int64, bool) {
	if o == nil || IsNil(o.ApplicationsUpdatedLastYear) {
		return nil, false
	}
	return o.ApplicationsUpdatedLastYear, true
}

// HasApplicationsUpdatedLastYear returns a boolean if a field has been set.
func (o *ApiSbomApplicationsHistoryMetricDTO) HasApplicationsUpdatedLastYear() bool {
	if o != nil && !IsNil(o.ApplicationsUpdatedLastYear) {
		return true
	}

	return false
}

// SetApplicationsUpdatedLastYear gets a reference to the given int64 and assigns it to the ApplicationsUpdatedLastYear field.
func (o *ApiSbomApplicationsHistoryMetricDTO) SetApplicationsUpdatedLastYear(v int64) {
	o.ApplicationsUpdatedLastYear = &v
}

// GetTotalScannedApplications returns the TotalScannedApplications field value if set, zero value otherwise.
func (o *ApiSbomApplicationsHistoryMetricDTO) GetTotalScannedApplications() int64 {
	if o == nil || IsNil(o.TotalScannedApplications) {
		var ret int64
		return ret
	}
	return *o.TotalScannedApplications
}

// GetTotalScannedApplicationsOk returns a tuple with the TotalScannedApplications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiSbomApplicationsHistoryMetricDTO) GetTotalScannedApplicationsOk() (*int64, bool) {
	if o == nil || IsNil(o.TotalScannedApplications) {
		return nil, false
	}
	return o.TotalScannedApplications, true
}

// HasTotalScannedApplications returns a boolean if a field has been set.
func (o *ApiSbomApplicationsHistoryMetricDTO) HasTotalScannedApplications() bool {
	if o != nil && !IsNil(o.TotalScannedApplications) {
		return true
	}

	return false
}

// SetTotalScannedApplications gets a reference to the given int64 and assigns it to the TotalScannedApplications field.
func (o *ApiSbomApplicationsHistoryMetricDTO) SetTotalScannedApplications(v int64) {
	o.TotalScannedApplications = &v
}

func (o ApiSbomApplicationsHistoryMetricDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiSbomApplicationsHistoryMetricDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApplicationsUpdatedLastMonth) {
		toSerialize["applicationsUpdatedLastMonth"] = o.ApplicationsUpdatedLastMonth
	}
	if !IsNil(o.ApplicationsUpdatedLastWeek) {
		toSerialize["applicationsUpdatedLastWeek"] = o.ApplicationsUpdatedLastWeek
	}
	if !IsNil(o.ApplicationsUpdatedLastYear) {
		toSerialize["applicationsUpdatedLastYear"] = o.ApplicationsUpdatedLastYear
	}
	if !IsNil(o.TotalScannedApplications) {
		toSerialize["totalScannedApplications"] = o.TotalScannedApplications
	}
	return toSerialize, nil
}

type NullableApiSbomApplicationsHistoryMetricDTO struct {
	value *ApiSbomApplicationsHistoryMetricDTO
	isSet bool
}

func (v NullableApiSbomApplicationsHistoryMetricDTO) Get() *ApiSbomApplicationsHistoryMetricDTO {
	return v.value
}

func (v *NullableApiSbomApplicationsHistoryMetricDTO) Set(val *ApiSbomApplicationsHistoryMetricDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableApiSbomApplicationsHistoryMetricDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableApiSbomApplicationsHistoryMetricDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiSbomApplicationsHistoryMetricDTO(val *ApiSbomApplicationsHistoryMetricDTO) *NullableApiSbomApplicationsHistoryMetricDTO {
	return &NullableApiSbomApplicationsHistoryMetricDTO{value: val, isSet: true}
}

func (v NullableApiSbomApplicationsHistoryMetricDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiSbomApplicationsHistoryMetricDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


